//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryWCFConsumer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesmanBO", Namespace="http://schemas.datacontract.org/2004/07/InventoryWCFService.InventoryBO")]
    [System.SerializableAttribute()]
    public partial class SalesmanBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CommissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesmanIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Commission {
            get {
                return this.CommissionField;
            }
            set {
                if ((this.CommissionField.Equals(value) != true)) {
                    this.CommissionField = value;
                    this.RaisePropertyChanged("Commission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesmanId {
            get {
                return this.SalesmanIdField;
            }
            set {
                if ((this.SalesmanIdField.Equals(value) != true)) {
                    this.SalesmanIdField = value;
                    this.RaisePropertyChanged("SalesmanId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBO", Namespace="http://schemas.datacontract.org/2004/07/InventoryWCFService.InventoryBO")]
    [System.SerializableAttribute()]
    public partial class CustomerBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesmanIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesmanId {
            get {
                return this.SalesmanIdField;
            }
            set {
                if ((this.SalesmanIdField.Equals(value) != true)) {
                    this.SalesmanIdField = value;
                    this.RaisePropertyChanged("SalesmanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int grade {
            get {
                return this.gradeField;
            }
            set {
                if ((this.gradeField.Equals(value) != true)) {
                    this.gradeField = value;
                    this.RaisePropertyChanged("grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdersBO", Namespace="http://schemas.datacontract.org/2004/07/InventoryWCFService.InventoryBO")]
    [System.SerializableAttribute()]
    public partial class OrdersBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PurchAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalesmanIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((this.OrderNoField.Equals(value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PurchAmt {
            get {
                return this.PurchAmtField;
            }
            set {
                if ((this.PurchAmtField.Equals(value) != true)) {
                    this.PurchAmtField = value;
                    this.RaisePropertyChanged("PurchAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalesmanId {
            get {
                return this.SalesmanIdField;
            }
            set {
                if ((this.SalesmanIdField.Equals(value) != true)) {
                    this.SalesmanIdField = value;
                    this.RaisePropertyChanged("SalesmanId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISalesman")]
    public interface ISalesman {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesman/InsertNewSalesman", ReplyAction="http://tempuri.org/ISalesman/InsertNewSalesmanResponse")]
        int InsertNewSalesman(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesman/InsertNewSalesman", ReplyAction="http://tempuri.org/ISalesman/InsertNewSalesmanResponse")]
        System.Threading.Tasks.Task<int> InsertNewSalesmanAsync(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesman/UpdateSalesmanInfo", ReplyAction="http://tempuri.org/ISalesman/UpdateSalesmanInfoResponse")]
        int UpdateSalesmanInfo(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesman/UpdateSalesmanInfo", ReplyAction="http://tempuri.org/ISalesman/UpdateSalesmanInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateSalesmanInfoAsync(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesman/DeleteSalesmanInfo", ReplyAction="http://tempuri.org/ISalesman/DeleteSalesmanInfoResponse")]
        int DeleteSalesmanInfo(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesman/DeleteSalesmanInfo", ReplyAction="http://tempuri.org/ISalesman/DeleteSalesmanInfoResponse")]
        System.Threading.Tasks.Task<int> DeleteSalesmanInfoAsync(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesmanChannel : InventoryWCFConsumer.ServiceReference1.ISalesman, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesmanClient : System.ServiceModel.ClientBase<InventoryWCFConsumer.ServiceReference1.ISalesman>, InventoryWCFConsumer.ServiceReference1.ISalesman {
        
        public SalesmanClient() {
        }
        
        public SalesmanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesmanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesmanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesmanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertNewSalesman(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman) {
            return base.Channel.InsertNewSalesman(newSalesman);
        }
        
        public System.Threading.Tasks.Task<int> InsertNewSalesmanAsync(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman) {
            return base.Channel.InsertNewSalesmanAsync(newSalesman);
        }
        
        public int UpdateSalesmanInfo(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman) {
            return base.Channel.UpdateSalesmanInfo(newSalesman);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSalesmanInfoAsync(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman) {
            return base.Channel.UpdateSalesmanInfoAsync(newSalesman);
        }
        
        public int DeleteSalesmanInfo(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman) {
            return base.Channel.DeleteSalesmanInfo(newSalesman);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSalesmanInfoAsync(InventoryWCFConsumer.ServiceReference1.SalesmanBO newSalesman) {
            return base.Channel.DeleteSalesmanInfoAsync(newSalesman);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICustomer")]
    public interface ICustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/InsertNewCustomer", ReplyAction="http://tempuri.org/ICustomer/InsertNewCustomerResponse")]
        int InsertNewCustomer(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/InsertNewCustomer", ReplyAction="http://tempuri.org/ICustomer/InsertNewCustomerResponse")]
        System.Threading.Tasks.Task<int> InsertNewCustomerAsync(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/UpdateCustomerInfo", ReplyAction="http://tempuri.org/ICustomer/UpdateCustomerInfoResponse")]
        int UpdateCustomerInfo(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/UpdateCustomerInfo", ReplyAction="http://tempuri.org/ICustomer/UpdateCustomerInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateCustomerInfoAsync(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/DeleteCustomerInfo", ReplyAction="http://tempuri.org/ICustomer/DeleteCustomerInfoResponse")]
        int DeleteCustomerInfo(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/DeleteCustomerInfo", ReplyAction="http://tempuri.org/ICustomer/DeleteCustomerInfoResponse")]
        System.Threading.Tasks.Task<int> DeleteCustomerInfoAsync(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerChannel : InventoryWCFConsumer.ServiceReference1.ICustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerClient : System.ServiceModel.ClientBase<InventoryWCFConsumer.ServiceReference1.ICustomer>, InventoryWCFConsumer.ServiceReference1.ICustomer {
        
        public CustomerClient() {
        }
        
        public CustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertNewCustomer(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer) {
            return base.Channel.InsertNewCustomer(NewCustomer);
        }
        
        public System.Threading.Tasks.Task<int> InsertNewCustomerAsync(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer) {
            return base.Channel.InsertNewCustomerAsync(NewCustomer);
        }
        
        public int UpdateCustomerInfo(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer) {
            return base.Channel.UpdateCustomerInfo(NewCustomer);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCustomerInfoAsync(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer) {
            return base.Channel.UpdateCustomerInfoAsync(NewCustomer);
        }
        
        public int DeleteCustomerInfo(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer) {
            return base.Channel.DeleteCustomerInfo(NewCustomer);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCustomerInfoAsync(InventoryWCFConsumer.ServiceReference1.CustomerBO NewCustomer) {
            return base.Channel.DeleteCustomerInfoAsync(NewCustomer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOrders")]
    public interface IOrders {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/InsertNewOrder", ReplyAction="http://tempuri.org/IOrders/InsertNewOrderResponse")]
        int InsertNewOrder(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/InsertNewOrder", ReplyAction="http://tempuri.org/IOrders/InsertNewOrderResponse")]
        System.Threading.Tasks.Task<int> InsertNewOrderAsync(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/UpdateOrdersInfo", ReplyAction="http://tempuri.org/IOrders/UpdateOrdersInfoResponse")]
        int UpdateOrdersInfo(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/UpdateOrdersInfo", ReplyAction="http://tempuri.org/IOrders/UpdateOrdersInfoResponse")]
        System.Threading.Tasks.Task<int> UpdateOrdersInfoAsync(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/DeleteOrdersInfo", ReplyAction="http://tempuri.org/IOrders/DeleteOrdersInfoResponse")]
        int DeleteOrdersInfo(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/DeleteOrdersInfo", ReplyAction="http://tempuri.org/IOrders/DeleteOrdersInfoResponse")]
        System.Threading.Tasks.Task<int> DeleteOrdersInfoAsync(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersChannel : InventoryWCFConsumer.ServiceReference1.IOrders, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersClient : System.ServiceModel.ClientBase<InventoryWCFConsumer.ServiceReference1.IOrders>, InventoryWCFConsumer.ServiceReference1.IOrders {
        
        public OrdersClient() {
        }
        
        public OrdersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertNewOrder(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders) {
            return base.Channel.InsertNewOrder(NewOrders);
        }
        
        public System.Threading.Tasks.Task<int> InsertNewOrderAsync(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders) {
            return base.Channel.InsertNewOrderAsync(NewOrders);
        }
        
        public int UpdateOrdersInfo(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders) {
            return base.Channel.UpdateOrdersInfo(NewOrders);
        }
        
        public System.Threading.Tasks.Task<int> UpdateOrdersInfoAsync(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders) {
            return base.Channel.UpdateOrdersInfoAsync(NewOrders);
        }
        
        public int DeleteOrdersInfo(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders) {
            return base.Channel.DeleteOrdersInfo(NewOrders);
        }
        
        public System.Threading.Tasks.Task<int> DeleteOrdersInfoAsync(InventoryWCFConsumer.ServiceReference1.OrdersBO NewOrders) {
            return base.Channel.DeleteOrdersInfoAsync(NewOrders);
        }
    }
}
